# https://starship.rs/presets/nerd-font
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$directory\
$git_branch\
$git_status\

$fill\

$custom\
$time
$character
"""

[fill]
symbol = " "

[os]
disabled = false
style = "cyan"
format = "[$symbol ]($style)"

[os.symbols]
Arch = ""

# [directory]
# format = "[$read_only]($read_only_style)[$path ]($style)"
# read_only = ""

# [git_branch]
# symbol = " "
# format = "[$symbol$branch ]($style)"

# [git_status]
# disabled = true

[custom.python_project]
when = '[[ -n "$VIRTUAL_ENV" ]]'
command = 'basename "$(dirname "$VIRTUAL_ENV")"'
format = '[ $output ]($style)'
style = 'green'
# [custom.python_project]
# when = '[[ -n "$VIRTUAL_ENV" ]]'
# command = 'basename "$(dirname "$VIRTUAL_ENV")"'
# format = '[ $output ]($style)'
# style = 'green'

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[ $time]($style)"

