[org/gnome/desktop/app-folders]
folder-children=['System', 'Utilities', 'YaST', 'Pardus', '63d41e0d-247e-48dd-b656-ca42fb08c4ea']

[org/gnome/desktop/app-folders/folders/63d41e0d-247e-48dd-b656-ca42fb08c4ea]
apps=['avahi-discover.desktop', 'bvnc.desktop', 'bssh.desktop', 'qv4l2.desktop', 'qvidcap.desktop']
name='Extras'
translate=false

[org/gnome/desktop/app-folders/folders/Pardus]
categories=['X-Pardus-Apps']
name='X-Pardus-Apps.directory'
translate=true

[org/gnome/desktop/app-folders/folders/System]
apps=['nm-connection-editor.desktop', 'org.gnome.baobab.desktop', 'org.gnome.DiskUtility.desktop', 'org.gnome.Logs.desktop', 'org.gnome.tweaks.desktop', 'org.gnome.SystemMonitor.desktop']
name='X-GNOME-Shell-System.directory'
translate=true

[org/gnome/desktop/app-folders/folders/Utilities]
apps=['org.gnome.Evince.desktop', 'org.gnome.font-viewer.desktop', 'org.gnome.Loupe.desktop', 'org.gnome.TextEditor.desktop', 'org.gnome.Characters.desktop', 'org.gnome.Papers.desktop']
name='X-GNOME-Shell-Utilities.directory'
translate=true

[org/gnome/desktop/app-folders/folders/YaST]
categories=['X-SuSE-YaST']
name='suse-yast.directory'
translate=true
