[org/gnome/shell/extensions/caffeine]
cli-toggle=true
countdown-timer=0
enable-fullscreen=false
indicator-position=0
indicator-position-index=0
indicator-position-max=2
inhibit-apps=['kitty.desktop']
show-indicator='always'
toggle-state=true
user-enabled=true
