[org/gnome/shell/extensions/dash-to-dock]
always-center-icons=true
animate-show-apps=true
application-counter-overrides-notifications=true
apply-custom-theme=false
apply-glossy-effect=false
autohide=true
autohide-in-fullscreen=true
background-color='rgb(0,0,0)'
background-opacity=0.20000000000000001
custom-background-color=false
custom-theme-customize-running-dots=true
custom-theme-running-dots-border-color='rgb(154,153,150)'
custom-theme-running-dots-border-width=0
custom-theme-running-dots-color='rgb(154,153,150)'
custom-theme-shrink=true
customize-alphas=true
dash-max-icon-size=50
disable-overview-on-startup=false
dock-fixed=false
dock-position='BOTTOM'
extend-height=false
height-fraction=0.75
hide-tooltip=true
hot-keys=false
icon-size-fixed=false
intellihide-mode='ALL_WINDOWS'
isolate-locations=true
isolate-monitors=false
isolate-workspaces=false
max-alpha=1.0
middle-click-action='launch'
min-alpha=0.10000000000000001
multi-monitor=true
preferred-monitor=-2
preferred-monitor-by-connector='HDMI-1'
preview-size-scale=0.69999999999999996
running-indicator-dominant-color=false
running-indicator-style='DOTS'
scroll-action='cycle-windows'
scroll-to-focused-application=true
shift-click-action='minimize'
shift-middle-click-action='previews'
show-apps-always-in-the-edge=false
show-apps-at-top=true
show-favorites=true
show-icons-emblems=true
show-icons-notifications-counter=true
show-mounts-network=true
show-running=true
show-show-apps-button=true
show-trash=false
show-windows-preview=true
transparency-mode='FIXED'
unity-backlit-items=false
workspace-agnostic-urgent-windows=true
