#!/usr/bin/env python3

from pathlib import Path


ARQUIVO = Path("user-settings.conf")
SCRIPT_INSTALL = Path("install-dconf.sh")


CHAVES = [
    "org/gnome/TextEditor",
    "org/gnome/desktop/app-folders",
    "org/gnome/desktop/input-sources",
    "org/gnome/desktop/interface",
    "org/gnome/desktop/peripherals",
    "org/gnome/desktop/wm",
    "org/gnome/mutter",
    "org/gnome/nautilus",
    "org/gnome/settings-daemon/plugins/media-keys",
    "org/gnome/shell",
    "org/gnome/shell/extensions/appindicator",
    "org/gnome/shell/extensions/blur-my-shell",
    "org/gnome/shell/extensions/caffeine",
    "org/gnome/shell/extensions/dash-to-dock",
    "org/gnome/shell/extensions/hide-cursor-elcste-com",
    "org/gnome/shell/extensions/user-theme",
    "org/gnome/shell/keybindings",
]

# Caminhos mais específicos devem ser testados primeiro.
CHAVES.sort(key=len, reverse=True)


def pertence(secao, chave):
    """Retorna True se 'secao' pertence à chave ou a um de seus descendentes."""
    return secao == chave or secao.startswith(chave + "/")


def nome_arquivo(chave):
    """Converte o último componente da chave no nome do arquivo."""
    return f"{chave.rsplit('/', 1)[-1]}.conf"


def encontrar_chave(secao):
    """Encontra o módulo mais específico ao qual uma seção pertence."""
    for chave in CHAVES:
        if pertence(secao, chave):
            return chave

    return None


def ler_blocos():
    """Lê o arquivo master e separa seu conteúdo por seção."""
    blocos = []

    secao = None
    linhas = []

    with ARQUIVO.open(encoding="utf-8") as arquivo:
        for linha in arquivo:
            linha = linha.rstrip("\n")

            # Uma nova seção começa.
            if linha.startswith("[") and linha.endswith("]"):
                if secao is not None:
                    blocos.append((secao, linhas))

                secao = linha[1:-1]
                linhas = [linha]
                continue

            if secao is not None:
                linhas.append(linha)

    # Última seção.
    if secao is not None:
        blocos.append((secao, linhas))

    return blocos


def gerar_arquivos(blocos):
    """Distribui os blocos entre os arquivos dos módulos."""
    modulos = {}
    ignorados = []

    for secao, linhas in blocos:
        chave = encontrar_chave(secao)

        if chave is None:
            ignorados.append(secao)
            continue

        modulos.setdefault(chave, []).extend(linhas)

    for chave in CHAVES:
        if chave not in modulos:
            continue

        arquivo = Path(nome_arquivo(chave))
        conteudo = "\n".join(modulos[chave]).rstrip() + "\n"

        arquivo.write_text(conteudo, encoding="utf-8")

        print(f"  {arquivo}")

    return ignorados


def gerar_script_install(modulos):
    """Gera o script responsável por carregar os módulos."""
    linhas = [
        "#!/usr/bin/env bash",
        "",
        "# Generated by dconf-split.py",
        "# Source: user-settings.conf",
        "",
    ]

    for chave in CHAVES:
        if chave not in modulos:
            continue

        arquivo = nome_arquivo(chave)

        linhas.extend(
            [
                f"# {arquivo.removesuffix('.conf')}",
                f"dconf load / < {arquivo}",
                "",
            ]
        )

    SCRIPT_INSTALL.write_text("\n".join(linhas), encoding="utf-8")
    SCRIPT_INSTALL.chmod(0o755)

    print(f"  {SCRIPT_INSTALL}")


def main():
    if not ARQUIVO.exists():
        print(f"Erro: arquivo não encontrado: {ARQUIVO}")
        return 1

    print(f"Lendo {ARQUIVO}...")
    blocos = ler_blocos()

    print(f"Encontradas {len(blocos)} seções.\n")
    print("Gerando arquivos:")

    # Descobre quais módulos foram realmente utilizados.
    modulos = {}

    for secao, linhas in blocos:
        chave = encontrar_chave(secao)

        if chave is not None:
            modulos.setdefault(chave, []).extend(linhas)

    # Gera os arquivos.
    for chave in CHAVES:
        if chave not in modulos:
            continue

        arquivo = Path(nome_arquivo(chave))
        conteudo = "\n".join(modulos[chave]).rstrip() + "\n"

        arquivo.write_text(conteudo, encoding="utf-8")

        print(f"  {arquivo}")

    # Gera o script de instalação.
    gerar_script_install(modulos)

    # Mostra se alguma seção ficou sem módulo.
    ignorados = [
        secao
        for secao, _ in blocos
        if encontrar_chave(secao) is None
    ]

    if ignorados:
        print("\nSeções sem módulo:")
        for secao in ignorados:
            print(f"  [{secao}]")

    print("\nConcluído.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
