[org/gnome/desktop/input-sources]
mru-sources=[('xkb', 'us+intl'), ('xkb', 'us'), ('xkb', 'br+dvorak')]
show-all-sources=true
sources=[('xkb', 'us+intl'), ('xkb', 'us'), ('xkb', 'br+dvorak')]
xkb-options=['terminate:ctrl_alt_bksp', 'lv3:ralt_switch']
