#!/usr/bin/env bash

# Generated by dconf-split.py
# Source: user-settings.conf

# hide-cursor-elcste-com
dconf load / < hide-cursor-elcste-com.conf

# media-keys
dconf load / < media-keys.conf

# blur-my-shell
dconf load / < blur-my-shell.conf

# appindicator
dconf load / < appindicator.conf

# dash-to-dock
dconf load / < dash-to-dock.conf

# user-theme
dconf load / < user-theme.conf

# caffeine
dconf load / < caffeine.conf

# vitals
dconf load / < vitals.conf

# input-sources
dconf load / < input-sources.conf

# notifications
dconf load / < notifications.conf

# app-folders
dconf load / < app-folders.conf

# peripherals
dconf load / < peripherals.conf

# interface
dconf load / < interface.conf

# keybindings
dconf load / < keybindings.conf

# TextEditor
dconf load / < TextEditor.conf

# wm
dconf load / < wm.conf

# mutter
dconf load / < mutter.conf

# shell
dconf load / < shell.conf
