[org/gnome/shell/keybindings]
focus-active-notification=@as []
open-new-window-application-0=@as []
open-new-window-application-1=@as []
open-new-window-application-2=@as []
open-new-window-application-3=@as []
open-new-window-application-4=@as []
open-new-window-application-5=@as []
open-new-window-application-6=@as []
open-new-window-application-7=@as []
open-new-window-application-8=@as []
open-new-window-application-9=@as []
open-new-window-application0=@as []
open-new-window-application1=@as []
open-new-window-application2=@as []
open-new-window-application3=@as []
open-new-window-application4=@as []
open-new-window-application5=@as []
open-new-window-application6=@as []
open-new-window-application7=@as []
open-new-window-application8=@as []
open-new-window-application9=@as []
shift-overview-down=@as []
shift-overview-up=@as []
show-screen-recording-ui=@as []
switch-to-application-0=@as []
switch-to-application-1=@as []
switch-to-application-2=@as []
switch-to-application-3=@as []
switch-to-application-4=@as []
switch-to-application-5=@as []
switch-to-application-6=@as []
switch-to-application-7=@as []
switch-to-application-8=@as []
switch-to-application-9=@as []
toggle-application-view=@as []
toggle-message-tray=@as []
toggle-quick-settings=['<Super>Escape']
