[org/gnome/settings-daemon/plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7/']
help=@as []
logout=@as []
magnifier=['<Alt>Return']
magnifier-zoom-in=['<Alt>equal']
magnifier-zoom-out=['<Alt>minus']
next=['AudioNext']
play=['AudioPlay']
previous=['AudioPrev']
screenreader=@as []
screensaver=@as []
volume-down=['AudioLowerVolume']
volume-mute=['AudioMute']
volume-up=['AudioRaiseVolume']
www=@as []

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Super>t'
command='kitty'
name='Kitty'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1]
binding='<Super>f'
command='firefox'
name='Firefox'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2]
binding='<Super>c'
command='code'
name='Code OSS'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3]
binding='<Super>e'
command='nautilus'
name='Nautilus'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5]
binding='<Super>r'
command='remmina'
name='Remmina'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom6]
binding='<Super>k'
command='keepassxc'
name='KeePassXC'

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom7]
binding='<Shift><Super>f'
command='firefox-developer-edition'
name='Firefox Dev'
