[org/gnome/desktop/peripherals/keyboard]
delay=uint32 325
numlock-state=true
repeat-interval=uint32 30

[org/gnome/desktop/peripherals/mouse]
double-click=282
speed=0.57419354838709669

[org/gnome/desktop/peripherals/touchpad]
two-finger-scrolling-enabled=true
